### ISSUE TITLE
Read temperatures in any precision

### ISSUE THREAD

**Issue by negroKiordi** [RobTillaart/DS18B20_INT#10]
Hello!
Reading the [datasheet.pdf](https://github.com/RobTillaart/DS18B20_INT/files/8958126/datasheet.pdf) at page 5 at "OPERATION - MEASURING TEMPERATURE" it explains that the temperatura is published as a fixpoint 16bit number regardless of its precision. So, I thought why limiting this beautifull tiny librarie to 9 bit.
The solution I have found is to return the temperatures as a int_16 number in centiC = C/100. 
So 125C will be 12500.

I have included some #defines to leave the user choose the precision:
```
`// Device resolution
#define TEMP_9_BIT  0x1F //  9 bit
#define TEMP_10_BIT 0x3F // 10 bit
#define TEMP_11_BIT 0x5F // 11 bit
#define TEMP_12_BIT 0x7F // 12 bit
#define TEMP_RESOLUTION		TEMP_12_BIT`

I have changed the following line in DS18B20_INT::begin(uint8_t retries) function
`   _oneWire->write(TEMP_RESOLUTION);  `

And I have changed the int16_t DS18B20_INT::getTempC(void) funtion as follows
```
int16_t DS18B20_INT::getTempC(void)
{
  _oneWire->reset();
  _oneWire->select(_deviceAddress);
  _oneWire->write(READSCRATCH);
//  Alejandro 9/6/2022
//  int16_t rawTemperature = ((int16_t)_oneWire->read()) << 8;  
//  rawTemperature |= _oneWire->read();

// Added by Alejandro 9/6/2022
  uint16_t temp_LSB = (uint16_t)_oneWire->read();
  int16_t rawTemperature = (int16_t)_oneWire->read();   //MSB
  rawTemperature = 	((rawTemperature << 8) | temp_LSB);	
  rawTemperature = ((int32_t)rawTemperature*100)>>4;
  
  _oneWire->reset();
  return rawTemperature;
}
```
The trick is to multiply by 100 before the right shift, by this the less significant numbers are preserved.
I have removed the error detection for the moment

I have tested it and seems to be OK.

**Comment by RobTillaart** [comment]
Thanks for the issue. 
Goal of this library was to be able to do fast integer measurements with a small footprint. No floats.

For the integer only the 9bit precision is sufficient.

Had a quick look and your proposal fits in the "no float" footprint thought. So I will give it some thoughts and come back to it later this week.

**Comment by RobTillaart** [comment]
@negroKiordi 
Reading again through your proposal I think the idea is good, but your proposal is breaking the interface,
My solution is to add a new function to the interface **int16_t getTempCentiC()** that does the job.
This leaves getTempC() as is.

Later today a develop branch will be available so you can test it.

**Comment by RobTillaart** [comment]
Develop branch created,
- added **getTempCentiC()** 
- added **setResolution(bits = 9)**
- added **getResolution()**

The get/set resolution allows runtime control of the resolution, instead of the compile time control.
(price is an extra byte in RAM + some bytes in PROGMEM)

I kept the math in 16 bits,   raw *100 / 16 === raw * 25 / 4;    

@negroKiordi 
Please verify if it works for you.

**Comment by negroKiordi** [comment]
Hi, looks good, I'll test it as soon as possible

**Comment by negroKiordi** [comment]
Hello,
I have tested. 
The footprints is smaller than the one I had proposed first, the way you kept the math in 16bit was smart!
I had a problem with rawdata, actually with the last version happens the same. 
I hadn't seen it because I had modified the librarie. Actually it could be a issue for the master branch.
I read the documentation but I found nothing about. 
In the datasheet said that data comes LSB first, so in a way confirms my suspects.
I modified the function as follows and the works well for me. I test in 9 and 12bit resolution.

```
int16_t DS18B20_INT::_readRaw(void)
{
  _oneWire->reset();
  _oneWire->select(_deviceAddress);
  _oneWire->write(READSCRATCH);
  int16_t rawTemperature = ((uint16_t)_oneWire->read());
  rawTemperature |= ((int16_t)_oneWire->read())<<8;
  _oneWire->reset();
  return rawTemperature;
}

```

**Comment by RobTillaart** [comment]
Thanks for testing, (which platform did you use?)
I will check the code again and do some testing.
(Need to find a sensor)

**Comment by negroKiordi** [comment]
I'm using Arduino IDE, Windows

**Comment by RobTillaart** [comment]
@negroKiordi 
Found a sensor, and a pull up resistor ;)
Your observation is right, the reading of the sensor swapped LSB and MSB 
I introduced that bug some time ago, a wakeup call to keep on testing with real hardware (thanks!)

I tested all examples with a sensor and an UNO and they now work as they should.
As the fix of reading is important, I bumped the version to 0.2.0.
