### ISSUE TITLE
device does not report -127 when disconnected

### ISSUE THREAD

**Issue by UptonAK** [RobTillaart/DS18B20_INT#13]
Hi Rob, thanks for the work you do. Sorry if this is not in fact an issue, maybe I just dont understand the library. 

for: DS18B20_INT.ino, DS18B20_simple.ino, and DS18B20_minimum.ino
when: complied and loaded, displays room temperature properly (ie 20.. 20.. 20.. 21.. 21..)
and when: sensor is disconnected via power, ground or data
results: a 0 C temperature being returned

As I understand, this library is a stripped down version of DallasTemperature.h which does report -127 when the sensor is disconnected or otherwise displays an error. I see that in DS18B20_INT.h there is an entry on line 30 with a define of -127 when the sensor is disconnected. 
0C is in the middle of my expected measurement range making it hard to filter out if a sensor is in fact disconnected. Having it report an extreme value like -127 makes it possible to tell.

**Comment by RobTillaart** [comment]
Thanks for this issue, as it is rather late i will dive into it tomorrow

**Comment by RobTillaart** [comment]
> As I understand, this library is a stripped down version of DallasTemperature.h 

Not exactly, I started with a stripped down version of the library to see if I could meet my requirements (minimal footprint).
Then I rewrote it into **DS18B20_RT**, essentially from scratch, while preserving the function names. 
From that one I derived an integer only version **DS18B20_INT** to prevent including the float math library.

So far the history, I will investigate now if I can add proper disconnect code.

**Comment by RobTillaart** [comment]
went through the code and the read functions depend on the **OneWIre** library.

If a sensor is disconnected it will read all zero's (possibly all 1's depending if the pull up resistor is also disconnected) as the library doesn't do CRC checking of the SCRATCHPAD.

The only way to be sure that a device is disconnected is to call **begin()** as it returns a bool to indicate an address has been found. I noticed that **setResolution()** calls **begin()** too but does not return the bool. I am going to fix that.

What can be done is IF the read returns zero, that it calls **begin()** again to see if the device is connected.
This is not 100% failsafe as it could happen that the disconnect is just during the **read()** and a moment later the wire is good again. 

A quick test showed that calling **begin()** takes 920 us on an UNO with no device connected so not too bad.
I'll make a development branch to give it a try.

**Comment by RobTillaart** [comment]
Develop branch here - https://github.com/RobTillaart/DS18B20_INT/tree/develop

Please give it a try

**Comment by UptonAK** [comment]
Downloaded branch

loaded DS18B20_minimum.ino
changed pin number and added 500ms delay to loop for readability

test 1: sensor connected
result: displays correct temperature reading every .5 seconds

test 2: sensor connected at boot, then disconnected, then reconnected
result: displays correct temperature reading every .5 seconds 
until: sensor disconnected
then: reports -1 value 
until: sensor reconnected
then: reports 85 for ~1 second
then: reports correct temperature
(see attachment at end)

test 3: sensor disconnected at boot, then conntected
result: reports -1 
until: sensor reconnected
result: continues to report -1


![Screen Shot 02-03-23 at 02 10 PM](https://user-images.githubusercontent.com/8830950/216728427-b59b5e04-2844-43c5-83ba-1c0c8a8c046f.PNG)

**Comment by UptonAK** [comment]
DS18B20_simple.ino yields the same results as above with the exception to test 2 where it does not display 85 at all.

**Comment by RobTillaart** [comment]
So in disconnected state the sensor does not always return zero. I assumed this from your first post.

That means that we must check connected state (call to begin) before the read instead of conditionally afterwards. Will create a new develop version later.

**Comment by RobTillaart** [comment]
@UptonAK 
Made changes in the develop branch
split up **begin()** to have a separate **isConnected()** function. 
This is called before **readTempC()** and it now reports **DEVICE_DISCONNECTED**.

Please download latest develop and give it a try,

**Comment by UptonAK** [comment]
![image](https://user-images.githubusercontent.com/8830950/216763806-0e099916-e2bc-462d-91bb-c1c7af1ebde5.png)
works!

-127 when disconnected. displays temp again on reconnect.

**Comment by RobTillaart** [comment]
Strange you still get one "85" measurement in it.

For commercial projects I often keep track of the critical sensor values and compare them with new measurements.
If the delta is much larger than reasonably expected it might have failed reading.
Strategies can be ignore, use last known value or retry reading. 

I will merge the develop branch a.s.a.p.

**Comment by RobTillaart** [comment]
Thanks for the support!

**Comment by RobTillaart** [comment]
> Strange you still get one "85" measurement in it.

Possible cause is that during request it was not connected and during read it was. 
That is a race condition that is hard to make fail safe in the library (see strategies above)

**Comment by UptonAK** [comment]
okay, but hang on, there's more. I was trying to write a test code to reliably replicate this last night but didnt finish. I dont know what to make of this but:
when running minimum or simple (fast poling) with no delay
and
I quickly connect and disconnect the ground pin to the sensor (1-2 Hz tapping)
then
occasional, and seems to be coincidentally with seeing the 85 value..
the sensor becomes a heater and becomes hot to the touch. 

I know that is hard to believe but I was able to do it manually several times. Once it starts reading again I saw values as high as 70C. 

running the main DS18B20_INT sketch does not do this. Also, adding a delay of 500ms to the loop in simple or minimum prevents it from happening, though I still see the 85 value. 
this should probably be a different issue.

**Comment by RobTillaart** [comment]
This is a different issue for sure.

Can you check if this also happens when you use the arduino temperature control library of Miles Burton?
I expect it it is a hardware problem not caused by the library.

(Hypothesis 1)
Inside The DS18 there is some processor  doing the actual measurement, and the handshake/protocol.
When flipping the power it goes through some boot sequence instead of a wait for command mode.

(Hypothesis 2)
The flipping causes loss of internal references, causing undefined states and thus undefined currents to flow. In the electronics. 

I must think if and how this can be analysed.

**Comment by RobTillaart** [comment]
Googled a bit and the value 85 seems to be the default power on value in the temperature register. Need to read dara sheet later today to verify. 

E.g.
https://www.stm32duino.com/viewtopic.php?t=848

So the value 85 is understood (sort of). I just don't understand why they are using a valid temperature for this as somehow I should be able to see if it is power up or a legit temperature.

**Comment by RobTillaart** [comment]
At least I hope it is detectable somehow from registers as a reread of 85 can be again a power on value.

**Comment by RobTillaart** [comment]
@UptonAK 

Not found any clues yet how to distinguish between 85C power on value and a genuine read. The datasheet gives no info on this topic. There is unfortunate no bit indicating that a conversion was running or ready or such.

However did find and interesting issue - https://github.com/cpetrich/counterfeit_DS18B20/issues/26

*"As for undocumented behavior, in my experience, genuine DS18B20 with bad power supply may produce valid readings, incorrect readings, 0x0550 (+85 °C) "start-up" readings, or undocumented 0x07ff (+127.9375 °C) or 0xffff (-0.0625 °C) readings."*

*"if power is bad, a 0x07ff is likely and if power is really bad the reading will probably be a 0x0550."*

So there are two more 'bad numbers' than expected. 

The way to handle a 85C is compare with previous if it is an expected value, if not do a reread.
In fact this is a strategy for all unexpected values.

**Comment by UptonAK** [comment]
Sorry, just digging into this after weekend. Probably is a bad sensor. I dont have any genuine ones but have two other from different orders/batches and a bare sensor (no cable, no housing) will try that today. 

forgot to mention, this is on ds18b20_int main as well as dev so it didnt just brake. Will dry with the other lib you suggested.

**Comment by UptonAK** [comment]
Okay. I spent over an hour on this. including rewiring setting up the arduino to randomly connect and disconnect the ground. Was only able to replicate once by manually tapping the grounds together. It is a very intermittent problem and likely not really an issue. 
there are a few forum posts about sensors getting hot. it looks rare and hardware related. 

moving on!
thanks again for the -127 fix
