### ISSUE TITLE
Correct README

### ISSUE THREAD

**Issue by GeoffState** [RobTillaart/DS18B20_INT#6]
in README.MD
- **int16_t readTempC()** returns temperature in whole degrees only. 
- should be 
- **int16_t getTempC()** returns temperature in whole degrees only.

**Comment by RobTillaart** [comment]
You're right - I'll fix it asap, there will be a minor release soon, possibly ~this week~ today.

develop branch made..

**Comment by RobTillaart** [comment]
Merged in 0.1.5

Thanks for pointing out
